project:
  type: book

execute:
  eval: true
  echo: true
  output: true
  freeze: auto  # auto: during global project renders, re-render only when source changes

book:
  title: "Get IRS data for PUF targeting"
  subtitle: "Create csv file"
  author: "Don Boyd"
  date: today
  date-format: long
  chapters:
    - index.qmd
    part: "IRS national data"
    chapters:
      - prepare_national.qmd
    part: "IRS state data"
    chapters:
      - prepare_state.qmd
    part: "IRS county data"
    chapters:
      - prepare_county.qmd
    part: "IRS Congressional District data"
    chapters:
      - prepare_cd.qmd

format:
  html:
    theme: cosmo
    code-fold: true    

editor_options:
  chunk_output_type: console


# possibly use this at start of each doc
# ---
# output: html_document
# editor_options: 
#   chunk_output_type: console
# ---

  
  